services:
- name: mock-target
  dns_sd_configs:
  - names:
    - $SERVER_URL
    refresh_interval: 10s
    type: A
    port: 7778
  scraper:
    endpoint: "/errors"
    refresh_interval: 10s
- name: periskop
  static_configs:
  - targets:
    - $SERVER_URL:7777
  scraper:
    endpoint: "/errors"
    refresh_interval: 10s